version: '3.8'

services:
  redis:
    image: redis
    container_name: redis-server
    ports:
      - "6379:6379"

  redis-insight:
    image: redislabs/redisinsight
    container_name: redis-insight
    ports:
      - "5540:5540"
    depends_on:
      - redis
