INSERT INTO countries ([country_id], [country_name], [region_id]) VALUES (N'AR', N'Argentina', '2');
INSERT INTO countries ([country_id], [country_name], [region_id]) VALUES (N'AU', N'Australia', '3');
INSERT INTO countries ([country_id], [country_name], [region_id]) VALUES (N'BE', N'Belgium', '1');
INSERT INTO countries ([country_id], [country_name], [region_id]) VALUES (N'BR', N'Brazil', '2');
INSERT INTO countries ([country_id], [country_name], [region_id]) VALUES (N'CA', N'Canada', '2');
INSERT INTO countries ([country_id], [country_name], [region_id]) VALUES (N'CH', N'Switzerland', '1');
INSERT INTO countries ([country_id], [country_name], [region_id]) VALUES (N'CN', N'China', '3');
INSERT INTO countries ([country_id], [country_name], [region_id]) VALUES (N'DE', N'Germany', '1');
INSERT INTO countries ([country_id], [country_name], [region_id]) VALUES (N'DK', N'Denmark', '1');
INSERT INTO countries ([country_id], [country_name], [region_id]) VALUES (N'EG', N'Egypt', '4');
INSERT INTO countries ([country_id], [country_name], [region_id]) VALUES (N'FR', N'France', '1');
INSERT INTO countries ([country_id], [country_name], [region_id]) VALUES (N'HK', N'HongKong', '3');
INSERT INTO countries ([country_id], [country_name], [region_id]) VALUES (N'IL', N'Israel', '4');
INSERT INTO countries ([country_id], [country_name], [region_id]) VALUES (N'IN', N'India', '3');
INSERT INTO countries ([country_id], [country_name], [region_id]) VALUES (N'IT', N'Italy', '1');
INSERT INTO countries ([country_id], [country_name], [region_id]) VALUES (N'JP', N'Japan', '3');
INSERT INTO countries ([country_id], [country_name], [region_id]) VALUES (N'KW', N'Kuwait', '4');
INSERT INTO countries ([country_id], [country_name], [region_id]) VALUES (N'MX', N'Mexico', '2');
INSERT INTO countries ([country_id], [country_name], [region_id]) VALUES (N'NG', N'Nigeria', '4');
INSERT INTO countries ([country_id], [country_name], [region_id]) VALUES (N'NL', N'Netherlands', '1');
INSERT INTO countries ([country_id], [country_name], [region_id]) VALUES (N'SG', N'Singapore', '3');
INSERT INTO countries ([country_id], [country_name], [region_id]) VALUES (N'UK', N'United Kingdom', '1');
INSERT INTO countries ([country_id], [country_name], [region_id]) VALUES (N'US', N'United States of America', '2');
INSERT INTO countries ([country_id], [country_name], [region_id]) VALUES (N'ZM', N'Zambia', '4');
INSERT INTO countries ([country_id], [country_name], [region_id]) VALUES (N'ZW', N'Zimbabwe', '4');
