CREATE DATABASE Shop
GO

USE Shop
GO 

CREATE TABLE products (
	id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	name NVARCHAR(255) NOT NULL,
	price FLOAT NOT NULL,
	remain_quantity INT NOT NULL
);

CREATE TABLE orders (
	id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	customer_id UNIQUEIDENTIFIER NOT NULL,
	order_reference NVARCHAR (20) NOT NULL,

	CONSTRAINT unqOrderReference UNIQUE (order_reference)
)

CREATE TABLE orders_items (
	id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	order_id UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES orders(id),
	product_id UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES products(id),
	quantity INT NOT NULL,
	price FLOAT NOT NULL
);